backend:
  name: github
  repo: macdonaldcalumj/website

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "technologies"
    label: "Technologies"
    folder: "content/technologies"
    create: true
    identifier_field: "name"
    fields:
      - {label: "ID", name: "id", widget: "id"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "ID", name: "id", widget: "id"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Date", name: "date", widget: "string"}
      - label: "Technology"
        name: "technology"
        widget: "relation"
        collection: "technologies"
        search_fields: ["name"]
        display_fields: ["name"]
        value_field: "id"
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Body", name: "body", widget: "markdown"}